kind: pipeline
name: uSail backend
type: docker

steps:
  - name: install
    image: node:16-alpine
    commands:
      - node -v
      - npm -v
      - npm install && npm cache clean --force --loglevel=error

  - name: testing
    image: node:16-alpine
    environment:
      db_host: postgres
      db_user: root
      db_password: pass
      db_database: uSail
      log_dir: '../logs'
      log_format: dev
      cors_origin: true
      cors_credentials: true
      secret_key: lkejlhsdfhgkjsdfhgkdjsfhgkd
    commands:
      - npm run test

  - name: lint
    environment:
      db_host: postgres
      db_user: root
      db_password: pass
      db_database: uSail
      log_dir: '../logs'
      log_format: dev
      cors_origin: true
      cors_credentials: true
      secret_key: lkejlhsdfhgkjsdfhgkdjsfhgkd
    image: node:16-alpine
    commands:
      - npm run lint

  - name: docker build django image and push
    image: plugins/docker
    settings:
      cache_from: registry.sliceofbits.com/uSail-Backend:latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      repo: registry.sliceofbits.com/uSail-Backend:latest
      registry: registry.sliceofbits.com/
      tags: latest
    when:
      branch:
        - main
      event:
        - push


services:
  - name: postgres
    image: postgres:13-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: uSail
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
