kind: pipeline
name: uSail backend
type: docker

steps:
  - name: install
    image: node:16-alpine
    commands:
      - node -v
      - npm -v
      - npm install && npm cache clean --force --loglevel=error

  - name: testing
    image: node:16-alpine
    environment:
      db_host: postgres
      db_user: root
      db_password: pass
      db_database: uSail
    commands:
      - npm install -g --save-dev jest supertest
      - npm run test

  - name: docker build django image and push
    image: plugins/docker
    settings:
      cache_from: registry.sliceofbits.com/u-sail-backend:latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      repo: registry.sliceofbits.com/u-sail-backend
      registry: registry.sliceofbits.com/
      tags: latest
    when:
      branch:
        - main
      event:
        - push


services:
  - name: postgres
    image: postgres:13-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: uSail
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
