version: '3.7'

services:
  server:
    image: registry.sliceofbits.com/uSail-Backend:latest
    container_name: UsailBackend
    ports:
      - '3000:3000'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_HOST: postgres
      MYSQL_DATABASE: uSail
    volumes:
      - ./:/app/configs
    restart: 'unless-stopped'
    networks:
      - backend
